### ISSUE TITLE
Module build fail TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by raycelgraterol** [nbfontana/ngx-currency#108]
Hello,
I am trying to build --prod my angular 8 project with ngx-currency npm but this error is raise: 

ERROR in ./node_modules/ngx-currency/fesm5/ngx-currency.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (C:\GitLab\controlkarar\node_modules\@angular-devkit\build-optimizer\src\transforms\crub-file.js:265:35)
    at checkNodeForDecorators (C:\GitLab\controlkarar\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:7:21)
    at visitNodes (C:\GitLab\controlkarar\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js16514:30)
    at Object.forEachChild (C:\GitLab\controlkarar\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typecript.js:16740:24)
    at checkNodeForDecorators (C:\GitLab\controlkarar\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\GitLab\controlkarar\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\GitLab\controlkarar\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16635:21)
    at checkNodeForDecorators (C:\GitLab\controlkarar\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\GitLab\controlkarar\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\GitLab\controlkarar\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16692:24)
    at checkNodeForDecorators (C:\GitLab\controlkarar\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\GitLab\controlkarar\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\GitLab\controlkarar\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16703:24)
    at checkNodeForDecorators (C:\GitLab\controlkarar\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\GitLab\controlkarar\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\GitLab\controlkarar\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16599:21)

Somebody help to continue using it.

**Comment by sebafra** [comment]
> Hello,
> I am trying to build --prod my angular 8 project with ngx-currency npm but this error is raise:
> 
> ERROR in ./node_modules/ngx-currency/fesm5/ngx-currency.js
> Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
> TypeError: Cannot read property 'kind' of undefined
> at isAngularDecoratorMetadataExpression (C:\GitLab\controlkarar\node_modules@angular-devkit\build-optimizer\src\transforms\crub-file.js:265:35)
> at checkNodeForDecorators (C:\GitLab\controlkarar\node_modules@angular-devkit\build-optimizer\src\transforms\scrub-file.js:7:21)
> at visitNodes (C:\GitLab\controlkarar\node_modules@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js16514:30)
> at Object.forEachChild (C:\GitLab\controlkarar\node_modules@angular-devkit\build-optimizer\node_modules\typescript\lib\typecript.js:16740:24)
> at checkNodeForDecorators (C:\GitLab\controlkarar\node_modules@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
> at visitNode (C:\GitLab\controlkarar\node_modules@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
> at Object.forEachChild (C:\GitLab\controlkarar\node_modules@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16635:21)
> at checkNodeForDecorators (C:\GitLab\controlkarar\node_modules@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
> at visitNode (C:\GitLab\controlkarar\node_modules@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
> at Object.forEachChild (C:\GitLab\controlkarar\node_modules@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16692:24)
> at checkNodeForDecorators (C:\GitLab\controlkarar\node_modules@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
> at visitNode (C:\GitLab\controlkarar\node_modules@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
> at Object.forEachChild (C:\GitLab\controlkarar\node_modules@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16703:24)
> at checkNodeForDecorators (C:\GitLab\controlkarar\node_modules@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
> at visitNode (C:\GitLab\controlkarar\node_modules@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
> at Object.forEachChild (C:\GitLab\controlkarar\node_modules@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16599:21)
> 
> Somebody help to continue using it.

Did you find a solution?

**Comment by Rudy1405** [comment]
Did you try to Downgrating ngx-currency to 2.0.1?
